owner: LeeYenhsun
repo: zenflux-monitoring

sites:
  - name: Google
    url: https://www.google.com
  - name: ZenFlux Main Site
    url: https://www.zenflux.tw

status-website:
  baseUrl: /zenflux-monitoring
  name: ZenFlux Monitoring
